<?php

use Illuminate\Database\Seeder;
use FairHub\NAZIONI as N;

class NAZIONISeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //INSERT INTO dw.dbo.NAZIONI \(([A-Za-z\_]+)\, ([A-Za-z\_]+)\, ([A-Za-z\_]+)\, ([A-Za-z\_]+)\, ([A-Za-z\_]+)\, ([A-Za-z\_]+)\, ([A-Za-z0-9\_]+)\) VALUES \(('[A-Za-z0-9]+')\, ('[\'A-Za-z0-9\-\_ \/\.]+')\, ('[A-Za-z0-9\(\)\-\_ \/\.\,\']+')\, ('[A-Za-z0-9\(\)\-\_ \/\.\,\']+')\, ([A-Za-z0-9\']+)\, ([A-Za-z0-9\']+)\, ([A-Za-z0-9\']+)\)\;
        //'$1'=>$8, '$2'=>$9, '$3'=>$10, '$4'=>$11, '$5'=>$12, '$6'=>$13, '$7'=>$13
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AD', 'naz_descr_ita'=>'ANDORRA', 'naz_descr_naz'=>'ANDORRA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AE', 'naz_descr_ita'=>'UNITED ARAB EMIRATES', 'naz_descr_naz'=>'UNITED ARAB EMIRATES', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AF', 'naz_descr_ita'=>'AFGHANISTAN', 'naz_descr_naz'=>'AFGHANISTAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AG', 'naz_descr_ita'=>'ANTIGUA AND BARBUDA', 'naz_descr_naz'=>'ANTIGUA AND BARBUDA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AI', 'naz_descr_ita'=>'ANGUILLA', 'naz_descr_naz'=>'ANGUILLA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AL', 'naz_descr_ita'=>'ALBANIA', 'naz_descr_naz'=>'ALBANIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AM', 'naz_descr_ita'=>'ARMENIA', 'naz_descr_naz'=>'ARMENIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AN', 'naz_descr_ita'=>'ANTILLE OLANDESI', 'naz_descr_naz'=>'NETHERLANDS ANTILLES', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AO', 'naz_descr_ita'=>'ANGOLA', 'naz_descr_naz'=>'ANGOLA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AQ', 'naz_descr_ita'=>'ANTARCTICA', 'naz_descr_naz'=>'ANTARCTICA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AR', 'naz_descr_ita'=>'ARGENTINA', 'naz_descr_naz'=>'ARGENTINA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AS', 'naz_descr_ita'=>'AMERICAN SAMOA', 'naz_descr_naz'=>'AMERICAN SAMOA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AT', 'naz_descr_ita'=>'AUSTRIA', 'naz_descr_naz'=>'AUSTRIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AU', 'naz_descr_ita'=>'AUSTRALIA', 'naz_descr_naz'=>'AUSTRALIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AW', 'naz_descr_ita'=>'ARUBA', 'naz_descr_naz'=>'ARUBA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'AZ', 'naz_descr_ita'=>'AZERBAIJAN', 'naz_descr_naz'=>'AZERBAIJAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BA', 'naz_descr_ita'=>'BOSNIA AND HERZEGOWINA', 'naz_descr_naz'=>'BOSNIA AND HERZEGOWINA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BB', 'naz_descr_ita'=>'BARBADOS', 'naz_descr_naz'=>'BARBADOS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BD', 'naz_descr_ita'=>'BANGLADESH', 'naz_descr_naz'=>'BANGLADESH', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BE', 'naz_descr_ita'=>'BELGIO', 'naz_descr_naz'=>'BELGIUM', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BF', 'naz_descr_ita'=>'BURKINA FASO', 'naz_descr_naz'=>'BURKINA FASO', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BG', 'naz_descr_ita'=>'BULGARIA', 'naz_descr_naz'=>'BULGARIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BH', 'naz_descr_ita'=>'BAHRAIN', 'naz_descr_naz'=>'BAHRAIN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BI', 'naz_descr_ita'=>'BURUNDI', 'naz_descr_naz'=>'BURUNDI', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BJ', 'naz_descr_ita'=>'BENIN', 'naz_descr_naz'=>'BENIN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BM', 'naz_descr_ita'=>'BERMUDA', 'naz_descr_naz'=>'BERMUDA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BN', 'naz_descr_ita'=>'BRUNEI DARUSSALAM', 'naz_descr_naz'=>'BRUNEI DARUSSALAM', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BO', 'naz_descr_ita'=>'BOLIVIA', 'naz_descr_naz'=>'BOLIVIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BR', 'naz_descr_ita'=>'BRASILE', 'naz_descr_naz'=>'BRAZIL', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BS', 'naz_descr_ita'=>'BAHAMAS', 'naz_descr_naz'=>'BAHAMAS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BT', 'naz_descr_ita'=>'BHUTAN', 'naz_descr_naz'=>'BHUTAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BV', 'naz_descr_ita'=>'BOUVET ISLAND', 'naz_descr_naz'=>'BOUVET ISLAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BW', 'naz_descr_ita'=>'BOTSWANA', 'naz_descr_naz'=>'BOTSWANA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BY', 'naz_descr_ita'=>'BELARUS', 'naz_descr_naz'=>'BELARUS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'BZ', 'naz_descr_ita'=>'BELIZE', 'naz_descr_naz'=>'BELIZE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CA', 'naz_descr_ita'=>'CANADA', 'naz_descr_naz'=>'CANADA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CC', 'naz_descr_ita'=>'COCOS (KEELING) ISLANDS', 'naz_descr_naz'=>'COCOS (KEELING) ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CD', 'naz_descr_ita'=>'CONGO, THE DEMOCRATIC REPUBLIC', 'naz_descr_naz'=>'CONGO, THE DEMOCRATIC REPUBLIC', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CF', 'naz_descr_ita'=>'REPUBBLICA CENTRO AFRICANA', 'naz_descr_naz'=>'CENTRAL AFRICAN REPUBLIC', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CG', 'naz_descr_ita'=>'CONGO', 'naz_descr_naz'=>'CONGO', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CH', 'naz_descr_ita'=>'SVIZZERA', 'naz_descr_naz'=>'SWITZERLAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CI', 'naz_descr_ita'=>'COTE D\'IVOIRE', 'naz_descr_naz'=>'COTE D\'IVOIRE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CK', 'naz_descr_ita'=>'COOK ISLANDS', 'naz_descr_naz'=>'COOK ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CL', 'naz_descr_ita'=>'CILE', 'naz_descr_naz'=>'CHILE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CM', 'naz_descr_ita'=>'CAMEROON', 'naz_descr_naz'=>'CAMEROON', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CN', 'naz_descr_ita'=>'CHINA', 'naz_descr_naz'=>'CHINA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CO', 'naz_descr_ita'=>'COLOMBIA', 'naz_descr_naz'=>'COLOMBIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CR', 'naz_descr_ita'=>'COSTA RICA', 'naz_descr_naz'=>'COSTA RICA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CU', 'naz_descr_ita'=>'CUBA', 'naz_descr_naz'=>'CUBA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CV', 'naz_descr_ita'=>'CAPO VERDE', 'naz_descr_naz'=>'CAPE VERDE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CX', 'naz_descr_ita'=>'CHRISTMAS ISLAND', 'naz_descr_naz'=>'CHRISTMAS ISLAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CY', 'naz_descr_ita'=>'CIPRO', 'naz_descr_naz'=>'CYPRUS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'CZ', 'naz_descr_ita'=>'REPUBBLICA CECA', 'naz_descr_naz'=>'CZECH REPUBLIC', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'DE', 'naz_descr_ita'=>'GERMANIA', 'naz_descr_naz'=>'GERMANY', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'DJ', 'naz_descr_ita'=>'DJIBOUTI', 'naz_descr_naz'=>'DJIBOUTI', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'DK', 'naz_descr_ita'=>'DANIMARCA', 'naz_descr_naz'=>'DENMARK', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'DM', 'naz_descr_ita'=>'DOMINICA', 'naz_descr_naz'=>'DOMINICA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'DO', 'naz_descr_ita'=>'DOMINICAN REPUBLIC', 'naz_descr_naz'=>'DOMINICAN REPUBLIC', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'DZ', 'naz_descr_ita'=>'ALGERIA', 'naz_descr_naz'=>'ALGERIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'EC', 'naz_descr_ita'=>'ECUADOR', 'naz_descr_naz'=>'ECUADOR', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'EE', 'naz_descr_ita'=>'ESTONIA', 'naz_descr_naz'=>'ESTONIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'EG', 'naz_descr_ita'=>'EGITTO', 'naz_descr_naz'=>'EGYPT', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'EH', 'naz_descr_ita'=>'WESTERN SAHARA', 'naz_descr_naz'=>'WESTERN SAHARA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'ER', 'naz_descr_ita'=>'ERITREA', 'naz_descr_naz'=>'ERITREA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'ES', 'naz_descr_ita'=>'SPAGNA', 'naz_descr_naz'=>'SPAIN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'ET', 'naz_descr_ita'=>'ETHIOPIA', 'naz_descr_naz'=>'ETHIOPIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'FI', 'naz_descr_ita'=>'FINLANDIA', 'naz_descr_naz'=>'FINLAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'FJ', 'naz_descr_ita'=>'FIJI', 'naz_descr_naz'=>'FIJI', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'FK', 'naz_descr_ita'=>'FALKLAND ISLANDS (MALVINAS)', 'naz_descr_naz'=>'FALKLAND ISLANDS (MALVINAS)', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'FM', 'naz_descr_ita'=>'MICRONESIA, FEDERATED STATES OF', 'naz_descr_naz'=>'MICRONESIA, FEDERATED STATES OF', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'FO', 'naz_descr_ita'=>'FAROE ISLANDS', 'naz_descr_naz'=>'FAROE ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'FR', 'naz_descr_ita'=>'FRANCIA', 'naz_descr_naz'=>'FRANCE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'FX', 'naz_descr_ita'=>'FRANCE METROPOLITAN', 'naz_descr_naz'=>'FRANCE METROPOLITAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GA', 'naz_descr_ita'=>'GABON', 'naz_descr_naz'=>'GABON', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GB', 'naz_descr_ita'=>'GRAN BRETAGNA', 'naz_descr_naz'=>'UNITED KINGDOM', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GD', 'naz_descr_ita'=>'GRENADA', 'naz_descr_naz'=>'GRENADA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GE', 'naz_descr_ita'=>'GEORGIA', 'naz_descr_naz'=>'GEORGIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GF', 'naz_descr_ita'=>'FRENCH GUIANA', 'naz_descr_naz'=>'FRENCH GUIANA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GH', 'naz_descr_ita'=>'GHANA', 'naz_descr_naz'=>'GHANA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GI', 'naz_descr_ita'=>'GIBRALTAR', 'naz_descr_naz'=>'GIBRALTAR', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GL', 'naz_descr_ita'=>'GREENLAND', 'naz_descr_naz'=>'GREENLAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GM', 'naz_descr_ita'=>'GAMBIA', 'naz_descr_naz'=>'GAMBIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GN', 'naz_descr_ita'=>'GUINEA', 'naz_descr_naz'=>'GUINEA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GP', 'naz_descr_ita'=>'GUADELOUPE', 'naz_descr_naz'=>'GUADELOUPE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GQ', 'naz_descr_ita'=>'EQUATORIAL GUINEA', 'naz_descr_naz'=>'EQUATORIAL GUINEA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GR', 'naz_descr_ita'=>'GRECIA', 'naz_descr_naz'=>'GREECE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GS', 'naz_descr_ita'=>'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'naz_descr_naz'=>'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GT', 'naz_descr_ita'=>'GUATEMALA', 'naz_descr_naz'=>'GUATEMALA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GU', 'naz_descr_ita'=>'GUAM', 'naz_descr_naz'=>'GUAM', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GW', 'naz_descr_ita'=>'GUINEA-BISSAU', 'naz_descr_naz'=>'GUINEA-BISSAU', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'GY', 'naz_descr_ita'=>'GUYANA', 'naz_descr_naz'=>'GUYANA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'HK', 'naz_descr_ita'=>'HONG KONG', 'naz_descr_naz'=>'HONG KONG', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'HM', 'naz_descr_ita'=>'HEARD AND MC DONALD ISLANDS', 'naz_descr_naz'=>'HEARD AND MC DONALD ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'HN', 'naz_descr_ita'=>'HONDURAS', 'naz_descr_naz'=>'HONDURAS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'HR', 'naz_descr_ita'=>'CROAZIA', 'naz_descr_naz'=>'CROATIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'HT', 'naz_descr_ita'=>'HAITI', 'naz_descr_naz'=>'HAITI', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'HU', 'naz_descr_ita'=>'UNGHERIA', 'naz_descr_naz'=>'HUNGARY', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'ID', 'naz_descr_ita'=>'INDONESIA', 'naz_descr_naz'=>'INDONESIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'IE', 'naz_descr_ita'=>'IRLANDA', 'naz_descr_naz'=>'IRELAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'IL', 'naz_descr_ita'=>'ISRAELE', 'naz_descr_naz'=>'ISRAEL', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'IN', 'naz_descr_ita'=>'INDIA', 'naz_descr_naz'=>'INDIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'IO', 'naz_descr_ita'=>'BRITISH INDIAN OCEAN TERRITORY', 'naz_descr_naz'=>'BRITISH INDIAN OCEAN TERRITORY', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'IQ', 'naz_descr_ita'=>'IRAQ', 'naz_descr_naz'=>'IRAQ', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'IR', 'naz_descr_ita'=>'IRAN (ISLAMIC REPUBLIC OF)', 'naz_descr_naz'=>'IRAN (ISLAMIC REPUBLIC OF)', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'IS', 'naz_descr_ita'=>'ISLANDA', 'naz_descr_naz'=>'ICELAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'IT', 'naz_descr_ita'=>'ITALIA', 'naz_descr_naz'=>'ITALY', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'JM', 'naz_descr_ita'=>'JAMAICA', 'naz_descr_naz'=>'JAMAICA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'JO', 'naz_descr_ita'=>'JORDAN', 'naz_descr_naz'=>'JORDAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'JP', 'naz_descr_ita'=>'GIAPPONE', 'naz_descr_naz'=>'JAPAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'KE', 'naz_descr_ita'=>'KENYA', 'naz_descr_naz'=>'KENYA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'KG', 'naz_descr_ita'=>'KYRGYZSTAN', 'naz_descr_naz'=>'KYRGYZSTAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'KH', 'naz_descr_ita'=>'CAMBODIA', 'naz_descr_naz'=>'CAMBODIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'KI', 'naz_descr_ita'=>'KIRIBATI', 'naz_descr_naz'=>'KIRIBATI', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'KM', 'naz_descr_ita'=>'COMOROS', 'naz_descr_naz'=>'COMOROS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'KN', 'naz_descr_ita'=>'SAINT KITTS AND NEVIS', 'naz_descr_naz'=>'SAINT KITTS AND NEVIS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'KP', 'naz_descr_ita'=>'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC', 'naz_descr_naz'=>'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'KR', 'naz_descr_ita'=>'KOREA, REPUBLIC OF', 'naz_descr_naz'=>'KOREA, REPUBLIC OF', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'KW', 'naz_descr_ita'=>'KUWAIT', 'naz_descr_naz'=>'KUWAIT', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'KY', 'naz_descr_ita'=>'CAYMAN ISLANDS', 'naz_descr_naz'=>'CAYMAN ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'KZ', 'naz_descr_ita'=>'KAZAKHSTAN', 'naz_descr_naz'=>'KAZAKHSTAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'LA', 'naz_descr_ita'=>'LAO PEOPLE\'S DEMOCRATIC REPUBL', 'naz_descr_naz'=>'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'LB', 'naz_descr_ita'=>'LIBANO', 'naz_descr_naz'=>'LEBANON', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'LC', 'naz_descr_ita'=>'SAINT LUCIA', 'naz_descr_naz'=>'SAINT LUCIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'LI', 'naz_descr_ita'=>'LIECHTENSTEIN', 'naz_descr_naz'=>'LIECHTENSTEIN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'LK', 'naz_descr_ita'=>'SRI LANKA', 'naz_descr_naz'=>'SRI LANKA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'LR', 'naz_descr_ita'=>'LIBERIA', 'naz_descr_naz'=>'LIBERIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'LS', 'naz_descr_ita'=>'LESOTHO', 'naz_descr_naz'=>'LESOTHO', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'LT', 'naz_descr_ita'=>'LITHUANIA', 'naz_descr_naz'=>'LITHUANIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'LU', 'naz_descr_ita'=>'LUSSEMBURGO', 'naz_descr_naz'=>'LUXEMBOURG', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'LV', 'naz_descr_ita'=>'LETTONIA', 'naz_descr_naz'=>'LATVIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'LY', 'naz_descr_ita'=>'LIBYAN ARAB JAMAHIRIYA', 'naz_descr_naz'=>'LIBYAN ARAB JAMAHIRIYA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MA', 'naz_descr_ita'=>'MAROCCO', 'naz_descr_naz'=>'MOROCCO', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MC', 'naz_descr_ita'=>'MONACO', 'naz_descr_naz'=>'MONACO', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MD', 'naz_descr_ita'=>'MOLDOVA, REPUBLIC OF', 'naz_descr_naz'=>'MOLDOVA, REPUBLIC OF', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'ME', 'naz_descr_ita'=>'MONTENEGRO', 'naz_descr_naz'=>'MONTENEGRO', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MG', 'naz_descr_ita'=>'MADAGASCAR', 'naz_descr_naz'=>'MADAGASCAR', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MH', 'naz_descr_ita'=>'MARSHALL ISLANDS', 'naz_descr_naz'=>'MARSHALL ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MK', 'naz_descr_ita'=>'MACEDONIA, THE FORMER YUGOSLAVIA', 'naz_descr_naz'=>'MACEDONIA, THE FORMER YUGOSLAVIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'ML', 'naz_descr_ita'=>'MALI', 'naz_descr_naz'=>'MALI', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MM', 'naz_descr_ita'=>'MYANMAR', 'naz_descr_naz'=>'MYANMAR', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MN', 'naz_descr_ita'=>'MONGOLIA', 'naz_descr_naz'=>'MONGOLIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MO', 'naz_descr_ita'=>'MACAU', 'naz_descr_naz'=>'MACAU', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MP', 'naz_descr_ita'=>'NORTHERN MARIANA ISLANDS', 'naz_descr_naz'=>'NORTHERN MARIANA ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MQ', 'naz_descr_ita'=>'MARTINIQUE', 'naz_descr_naz'=>'MARTINIQUE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MR', 'naz_descr_ita'=>'MAURITANIA', 'naz_descr_naz'=>'MAURITANIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MS', 'naz_descr_ita'=>'MONTSERRAT', 'naz_descr_naz'=>'MONTSERRAT', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MT', 'naz_descr_ita'=>'MALTA', 'naz_descr_naz'=>'MALTA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MU', 'naz_descr_ita'=>'MAURITIUS', 'naz_descr_naz'=>'MAURITIUS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MV', 'naz_descr_ita'=>'MALDIVES', 'naz_descr_naz'=>'MALDIVES', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MW', 'naz_descr_ita'=>'MALAWI', 'naz_descr_naz'=>'MALAWI', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MX', 'naz_descr_ita'=>'MESSICO', 'naz_descr_naz'=>'MEXICO', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MY', 'naz_descr_ita'=>'MALAYSIA', 'naz_descr_naz'=>'MALAYSIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'MZ', 'naz_descr_ita'=>'MOZAMBIQUE', 'naz_descr_naz'=>'MOZAMBIQUE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NA', 'naz_descr_ita'=>'NAMIBIA', 'naz_descr_naz'=>'NAMIBIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NC', 'naz_descr_ita'=>'NEW CALEDONIA', 'naz_descr_naz'=>'NEW CALEDONIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NE', 'naz_descr_ita'=>'NIGER', 'naz_descr_naz'=>'NIGER', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NF', 'naz_descr_ita'=>'NORFOLK ISLAND', 'naz_descr_naz'=>'NORFOLK ISLAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NG', 'naz_descr_ita'=>'NIGERIA', 'naz_descr_naz'=>'NIGERIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NI', 'naz_descr_ita'=>'NICARAGUA', 'naz_descr_naz'=>'NICARAGUA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NL', 'naz_descr_ita'=>'OLANDA', 'naz_descr_naz'=>'NETHERLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NO', 'naz_descr_ita'=>'NORVEGIA', 'naz_descr_naz'=>'NORWAY', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NP', 'naz_descr_ita'=>'NEPAL', 'naz_descr_naz'=>'NEPAL', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NR', 'naz_descr_ita'=>'NAURU', 'naz_descr_naz'=>'NAURU', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NU', 'naz_descr_ita'=>'NIUE', 'naz_descr_naz'=>'NIUE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'NZ', 'naz_descr_ita'=>'NEW ZEALAND', 'naz_descr_naz'=>'NEW ZEALAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'OM', 'naz_descr_ita'=>'OMAN', 'naz_descr_naz'=>'OMAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PA', 'naz_descr_ita'=>'PANAMA', 'naz_descr_naz'=>'PANAMA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PE', 'naz_descr_ita'=>'PERU', 'naz_descr_naz'=>'PERU', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PF', 'naz_descr_ita'=>'FRENCH POLYNESIA', 'naz_descr_naz'=>'FRENCH POLYNESIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PG', 'naz_descr_ita'=>'PAPUA NEW GUINEA', 'naz_descr_naz'=>'PAPUA NEW GUINEA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PH', 'naz_descr_ita'=>'FILIPPINE', 'naz_descr_naz'=>'PHILIPPINES', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PK', 'naz_descr_ita'=>'PAKISTAN', 'naz_descr_naz'=>'PAKISTAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PL', 'naz_descr_ita'=>'POLONIA', 'naz_descr_naz'=>'POLAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PM', 'naz_descr_ita'=>'ST. PIERRE AND MIQUELON', 'naz_descr_naz'=>'ST. PIERRE AND MIQUELON', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PN', 'naz_descr_ita'=>'PITCAIRN', 'naz_descr_naz'=>'PITCAIRN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PR', 'naz_descr_ita'=>'PUERTO RICO', 'naz_descr_naz'=>'PUERTO RICO', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PS', 'naz_descr_ita'=>'PALESTINA', 'naz_descr_naz'=>'PALESTINA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PT', 'naz_descr_ita'=>'PORTOGALLO', 'naz_descr_naz'=>'PORTUGAL', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PW', 'naz_descr_ita'=>'PALAU', 'naz_descr_naz'=>'PALAU', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'PY', 'naz_descr_ita'=>'PARAGUAY', 'naz_descr_naz'=>'PARAGUAY', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'QA', 'naz_descr_ita'=>'QATAR', 'naz_descr_naz'=>'QATAR', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'RE', 'naz_descr_ita'=>'REUNION', 'naz_descr_naz'=>'REUNION', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'RO', 'naz_descr_ita'=>'ROMANIA', 'naz_descr_naz'=>'ROMANIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'RS', 'naz_descr_ita'=>'SERBIA', 'naz_descr_naz'=>'SERBIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'RU', 'naz_descr_ita'=>'RUSSIAN FEDERATION', 'naz_descr_naz'=>'RUSSIAN FEDERATION', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'RW', 'naz_descr_ita'=>'RWANDA', 'naz_descr_naz'=>'RWANDA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SA', 'naz_descr_ita'=>'SAUDI ARABIA', 'naz_descr_naz'=>'SAUDI ARABIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SB', 'naz_descr_ita'=>'SOLOMON ISLANDS', 'naz_descr_naz'=>'SOLOMON ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SC', 'naz_descr_ita'=>'SEYCHELLES', 'naz_descr_naz'=>'SEYCHELLES', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SD', 'naz_descr_ita'=>'SUDAN', 'naz_descr_naz'=>'SUDAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SE', 'naz_descr_ita'=>'SVEZIA', 'naz_descr_naz'=>'SWEDEN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SG', 'naz_descr_ita'=>'SINGAPORE', 'naz_descr_naz'=>'SINGAPORE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SH', 'naz_descr_ita'=>'ST. HELENA', 'naz_descr_naz'=>'ST. HELENA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SI', 'naz_descr_ita'=>'SLOVENIA', 'naz_descr_naz'=>'SLOVENIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SJ', 'naz_descr_ita'=>'SVALBARD AND JAN MAYEN ISLANDS', 'naz_descr_naz'=>'SVALBARD AND JAN MAYEN ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SK', 'naz_descr_ita'=>'SLOVAKIA', 'naz_descr_naz'=>'SLOVAKIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SL', 'naz_descr_ita'=>'SIERRA LEONE', 'naz_descr_naz'=>'SIERRA LEONE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SM', 'naz_descr_ita'=>'SAN MARINO', 'naz_descr_naz'=>'SAN MARINO', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SN', 'naz_descr_ita'=>'SENEGAL', 'naz_descr_naz'=>'SENEGAL', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SO', 'naz_descr_ita'=>'SOMALIA', 'naz_descr_naz'=>'SOMALIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SR', 'naz_descr_ita'=>'SURINAME', 'naz_descr_naz'=>'SURINAME', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'ST', 'naz_descr_ita'=>'SAO TOME AND PRINCIPE', 'naz_descr_naz'=>'SAO TOME AND PRINCIPE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SV', 'naz_descr_ita'=>'EL SALVADOR', 'naz_descr_naz'=>'EL SALVADOR', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SY', 'naz_descr_ita'=>'SYRIAN ARAB REPUBLIC', 'naz_descr_naz'=>'SYRIAN ARAB REPUBLIC', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'SZ', 'naz_descr_ita'=>'SWAZILAND', 'naz_descr_naz'=>'SWAZILAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TC', 'naz_descr_ita'=>'TURKS AND CAICOS ISLANDS', 'naz_descr_naz'=>'TURKS AND CAICOS ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TD', 'naz_descr_ita'=>'CHAD', 'naz_descr_naz'=>'CHAD', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TF', 'naz_descr_ita'=>'FRENCH SOUTHERN TERRITORIES', 'naz_descr_naz'=>'FRENCH SOUTHERN TERRITORIES', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TG', 'naz_descr_ita'=>'TOGO', 'naz_descr_naz'=>'TOGO', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TH', 'naz_descr_ita'=>'THAILAND', 'naz_descr_naz'=>'THAILAND', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TJ', 'naz_descr_ita'=>'TAJIKISTAN', 'naz_descr_naz'=>'TAJIKISTAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TK', 'naz_descr_ita'=>'TOKELAU', 'naz_descr_naz'=>'TOKELAU', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TM', 'naz_descr_ita'=>'TURKMENISTAN', 'naz_descr_naz'=>'TURKMENISTAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TN', 'naz_descr_ita'=>'TUNISIA', 'naz_descr_naz'=>'TUNISIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TO', 'naz_descr_ita'=>'TONGA', 'naz_descr_naz'=>'TONGA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TP', 'naz_descr_ita'=>'EAST TIMOR', 'naz_descr_naz'=>'EAST TIMOR', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TR', 'naz_descr_ita'=>'TURCHIA', 'naz_descr_naz'=>'TURKEY', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TT', 'naz_descr_ita'=>'TRINIDAD AND TOBAGO', 'naz_descr_naz'=>'TRINIDAD AND TOBAGO', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TV', 'naz_descr_ita'=>'TUVALU', 'naz_descr_naz'=>'TUVALU', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TW', 'naz_descr_ita'=>'TAIWAN, REPUBLIC OF CHINA', 'naz_descr_naz'=>'TAIWAN, REPUBLIC OF CHINA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'TZ', 'naz_descr_ita'=>'TANZANIA, UNITED REPUBLIC OF', 'naz_descr_naz'=>'TANZANIA, UNITED REPUBLIC OF', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'UA', 'naz_descr_ita'=>'UKRAINE', 'naz_descr_naz'=>'UKRAINE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'UG', 'naz_descr_ita'=>'UGANDA', 'naz_descr_naz'=>'UGANDA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'UM', 'naz_descr_ita'=>'UNITED STATES MINOR OUTLYING ISLANDS', 'naz_descr_naz'=>'UNITED STATES MINOR OUTLYING ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'US', 'naz_descr_ita'=>'STATI UNITI - USA', 'naz_descr_naz'=>'UNITED STATES - USA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'UY', 'naz_descr_ita'=>'URUGUAY', 'naz_descr_naz'=>'URUGUAY', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'UZ', 'naz_descr_ita'=>'UZBEKISTAN', 'naz_descr_naz'=>'UZBEKISTAN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'VA', 'naz_descr_ita'=>'VATICAN CITY STATE (HOLY SEE)', 'naz_descr_naz'=>'VATICAN CITY STATE (HOLY SEE)', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'VC', 'naz_descr_ita'=>'SAINT VINCENT AND THE GRENADIN', 'naz_descr_naz'=>'SAINT VINCENT AND THE GRENADIN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'VE', 'naz_descr_ita'=>'VENEZUELA', 'naz_descr_naz'=>'VENEZUELA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'VG', 'naz_descr_ita'=>'VIRGIN ISLANDS (BRITISH)', 'naz_descr_naz'=>'VIRGIN ISLANDS (BRITISH)', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'VI', 'naz_descr_ita'=>'VIRGIN ISLANDS (U.S.)', 'naz_descr_naz'=>'VIRGIN ISLANDS (U.S.)', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'VN', 'naz_descr_ita'=>'VIET NAM', 'naz_descr_naz'=>'VIET NAM', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'VU', 'naz_descr_ita'=>'VANUATU', 'naz_descr_naz'=>'VANUATU', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'WF', 'naz_descr_ita'=>'WALLIS AND FUTUNA ISLANDS', 'naz_descr_naz'=>'WALLIS AND FUTUNA ISLANDS', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'WS', 'naz_descr_ita'=>'SAMOA', 'naz_descr_naz'=>'SAMOA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'YE', 'naz_descr_ita'=>'YEMEN', 'naz_descr_naz'=>'YEMEN', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'YT', 'naz_descr_ita'=>'MAYOTTE', 'naz_descr_naz'=>'MAYOTTE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'ZA', 'naz_descr_ita'=>'SUD AFRICA', 'naz_descr_naz'=>'SOUTH AFRICA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'ZM', 'naz_descr_ita'=>'ZAMBIA', 'naz_descr_naz'=>'ZAMBIA', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'ZW', 'naz_descr_ita'=>'ZIMBABWE', 'naz_descr_naz'=>'ZIMBABWE', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
        N::create(['naz_ute'=>'01', 'naz_nazione'=>'ZZ', 'naz_descr_ita'=>'SAINT MARTIN FRENCH WEST INDIES', 'naz_descr_naz'=>'SAINT MARTIN FRENCH WEST INDIES', 'naz_valuta'=>null, 'naz_lingua'=>null, 'naz_nazione_03'=>null]);
    }
}
